# Pull requests and related issues that are given these labels will
# be included in releases in the given categories.
labels:
  - name: important
    highlight: true
  - name: breaking
    description: 🚨 Breaking changes
  - name: bug
    description: 🐛 Bug fixes
  - name: feature
    description: 🏅 New features
