name: Container breakage
on:
  workflow_dispatch:

jobs: 
  k8sdemo:
    container:
      image: ubuntu:20.04
    runs-on: [ ubuntu-latest ] 
    steps:
      - run: |
          apt-get update
          apt-get install git -y
      - uses: actions/checkout@v2
      - run: pwd
