# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      bar:
        description: 'this is an input'

env:
  foo: BAR
  zzz: ${{ github.event.inputs.bar }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        asdf: [ BARz ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world!
          env
          dotnet --version
      - uses: ethomson/env-action@v1
      - run: echo hi
        if: ${{ matrix.asdf == env.foo }}
      - run: echo 42 > data.txt
      - uses: actions/upload-artifact@v2
        with:
          name: data
          path: data.txt

  stage:
    runs-on: ubuntu-latest
    needs: [ build ]
    environment:
      name: staging
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: data
      - run: |
          ls -FlasR
          cat data.txt
      - name: Staging
        run: echo Staged
 
  publish:
    runs-on: ubuntu-latest
    needs: [ stage ]
    environment:
      name: prod
    steps:
      - name: Publish
        run: echo Published
