# This is a basic workflow to help you get started with Actions

name: Timer

# Controls when the workflow will run
on:
  schedule:
  - cron: "*/10 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hello:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: echo Hello, world!
