on: [push]
jobs:
  hello_world_job:
    strategy:
      matrix:
        os: [ windows-2016, windows-2019, windows-2022 ]
    runs-on: ${{ matrix.os }}
    name: Git version
    steps:
      - run: git --version
